"""add table diary_analyses

Revision ID: 6317cc6906b0
Revises: 01c61f43a0a3
Create Date: 2026-05-23 15:34:52.920714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6317cc6906b0'
down_revision: Union[str, Sequence[str], None] = '01c61f43a0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=5), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Integer(), nullable=True),
    sa.Column('total_cholesterol', sa.Integer(), nullable=True),
    sa.Column('hdl', sa.Integer(), nullable=True),
    sa.Column('smoking', sa.String(length=10), nullable=True),
    sa.Column('diabetes_history', sa.Boolean(), nullable=True),
    sa.Column('hypertension_medication', sa.Boolean(), nullable=True),
    sa.Column('family_history_cvd', sa.Boolean(), nullable=True),
    sa.Column('family_history_dm', sa.Boolean(), nullable=True),
    sa.Column('burnout_count', sa.Integer(), nullable=False),
    sa.Column('sleep_lack_count', sa.Integer(), nullable=False),
    sa.Column('insomnia_count', sa.Integer(), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('sedentary_count', sa.Integer(), nullable=False),
    sa.Column('exercise_count', sa.Integer(), nullable=False),
    sa.Column('breakfast_skip_count', sa.Integer(), nullable=False),
    sa.Column('alcohol_count', sa.Integer(), nullable=False),
    sa.Column('msk_pain_count', sa.Integer(), nullable=False),
    sa.Column('vegetable_count', sa.Integer(), nullable=False),
    sa.Column('regular_meal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_id')
    )
    op.create_index(op.f('ix_diary_analyses_user_id'), 'diary_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary_analyses_user_id'), table_name='diary_analyses')
    op.drop_table('diary_analyses')
    # ### end Alembic commands ###
