"""add health info columns to users

Revision ID: 8be7cc33fe6f
Revises: 6317cc6906b0
Create Date: 2026-05-24 13:28:58.004214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be7cc33fe6f'
down_revision: Union[str, Sequence[str], None] = '6317cc6906b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('waist_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('sbp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_cholesterol', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hdl', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('smoking', sa.String(), nullable=True))
    op.add_column('users', sa.Column('diabetes_history', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('hypertension_medication', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('family_history_cvd', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('family_history_dm', sa.Boolean(), nullable=True))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('users', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'family_history_dm')
    op.drop_column('users', 'family_history_cvd')
    op.drop_column('users', 'hypertension_medication')
    op.drop_column('users', 'diabetes_history')
    op.drop_column('users', 'smoking')
    op.drop_column('users', 'hdl')
    op.drop_column('users', 'total_cholesterol')
    op.drop_column('users', 'sbp')
    op.drop_column('users', 'waist_cm')
    op.drop_column('users', 'bmi')
    # ### end Alembic commands ###
