"""create diary_nlp_metrics

Revision ID: 98f4adb861e0
Revises: 8be7cc33fe6f
Create Date: 2026-05-26 22:58:30.631717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f4adb861e0'
down_revision: Union[str, Sequence[str], None] = '8be7cc33fe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_nlp_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('burnout_count', sa.Integer(), nullable=False),
    sa.Column('sleep_lack_count', sa.Integer(), nullable=False),
    sa.Column('insomnia_count', sa.Integer(), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('sedentary_count', sa.Integer(), nullable=False),
    sa.Column('exercise_count', sa.Integer(), nullable=False),
    sa.Column('breakfast_skip_count', sa.Integer(), nullable=False),
    sa.Column('alcohol_count', sa.Integer(), nullable=False),
    sa.Column('msk_pain_count', sa.Integer(), nullable=False),
    sa.Column('vegetable_count', sa.Integer(), nullable=False),
    sa.Column('regular_meal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_nlp_metrics_date'), 'diary_nlp_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_diary_nlp_metrics_diary_id'), 'diary_nlp_metrics', ['diary_id'], unique=True)
    op.create_index(op.f('ix_diary_nlp_metrics_id'), 'diary_nlp_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_diary_nlp_metrics_user_id'), 'diary_nlp_metrics', ['user_id'], unique=False)
    op.drop_index(op.f('ix_diary_analyses_user_id'), table_name='diary_analyses')
    op.drop_table('diary_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diary_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('bmi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sbp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cholesterol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hdl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smoking', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('diabetes_history', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hypertension_medication', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family_history_cvd', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family_history_dm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('burnout_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sleep_lack_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insomnia_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sedentary_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('breakfast_skip_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alcohol_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('msk_pain_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vegetable_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('regular_meal_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], name=op.f('diary_analyses_diary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('diary_analyses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('diary_analyses_pkey')),
    sa.UniqueConstraint('diary_id', name=op.f('diary_analyses_diary_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_diary_analyses_user_id'), 'diary_analyses', ['user_id'], unique=False)
    op.drop_index(op.f('ix_diary_nlp_metrics_user_id'), table_name='diary_nlp_metrics')
    op.drop_index(op.f('ix_diary_nlp_metrics_id'), table_name='diary_nlp_metrics')
    op.drop_index(op.f('ix_diary_nlp_metrics_diary_id'), table_name='diary_nlp_metrics')
    op.drop_index(op.f('ix_diary_nlp_metrics_date'), table_name='diary_nlp_metrics')
    op.drop_table('diary_nlp_metrics')
    # ### end Alembic commands ###
